name: nutriby
description: "A smart solution to prevent stunting."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

#====================================================================
# DEPENDENCIES
#====================================================================
dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  flutter_secure_storage: ^9.1.1
  intl: ^0.19.0

  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2

#====================================================================
# DEV DEPENDENCIES
#====================================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

#====================================================================
# APP ICON CONFIG (JANGAN TARUH DI DALAM flutter:)
#====================================================================
flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo/logo_NutriBy.png"

#====================================================================
# FLUTTER
#====================================================================
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
